In [4]:
#numpy
#array-it stores always together
#diffrence between array and list
#array-always takes same type of datatype
#2.do all mathematical function easliy and fast
#3.consume less memory more than list
#4. a list is easier to modify ,easier to delete and add an element than an array does
#5 a list can have nested data with different size but in array it is not possible always take same size of data

import numpy as np
a=np.array([20,30,40])
b=np.array([26,34,45])
print(a)
print(b)
print(a+b)

[20 30 40]
[26 34 45]
[46 64 85]


In [5]:
a=np.array([2,3.4,5])
a

array([2. , 3.4, 5. ])

In [10]:
#numpy-creating arrays, slicing and attributes
import numpy as np

arr=np.array([[12,34,43,32],[22,33,23,33],[22,33,45,55]])
print(arr)


[[12 34 43 32]
 [22 33 23 33]
 [22 33 45 55]]
[[12 34 43 32]]


In [13]:
arr=np.array([12,34,43,32])
print(arr[0:2])# slicing

[12 34]


In [14]:
arr=np.array([[12,34,43,32],[22,33,23,33]])
print(arr[0:2,0:2])

[[12 34]
 [22 33]]


In [15]:
arr=np.array([[12,34,43,32],[22,33,23,33]])
print(arr[1,2:])


[23 33]


In [24]:
# inspecting an array
arr=np.array([[12,34,43,32],[22,33,23,33],[22,33,45,55]])
print(arr[2,1:3])
print(np.shape(arr))# number of rows and number of coloumn
print(np.size(arr))# total no. of elements
print(np.ndim(arr))# two dimensional
print(len(arr))# length od arr
print(type(arr))
print(arr.dtype)
print(arr.astype(float)) or int or string# conversion of array


[33 45]
(3, 4)
12
2
3
<class 'numpy.ndarray'>
int32
[[12. 34. 43. 32.]
 [22. 33. 23. 33.]
 [22. 33. 45. 55.]]


In [26]:
# mathematical operations and functions on arrays
import numpy as np
arr1= np.array([23,21,33,44])
arr2=np.array([77,44,33,22])
print(arr1+arr2)
print(np.add(arr1,arr2))


[100  65  66  66]
[100  65  66  66]


In [2]:
import numpy as np
arr1= np.array([[23,21],[33,44]])
arr2=np.array([[77,44],[33,22]])
print(np.subtract(arr1,arr2))

[[-54 -23]
 [  0  22]]


In [11]:
import numpy as np
arr1=np.array([20,30,40,50])
arr2=np.array([2])
print(np.power(arr1,arr2))


[ 400  900 1600 2500]


In [12]:
import numpy as np
arr1=np.array([49,16,36])
print(np.sqrt(arr1))

[7. 4. 6.]


In [16]:
#combining and splitting arrays
#concatenate
import numpy as np
arr1=np.array([12,13,14])
arr2=np.array([15,16,17])
print(np.concatenate([arr1,arr2]))
print(np.concatenate([arr1,arr2],axis=0))

[12 13 14 15 16 17]
[12 13 14 15 16 17]


In [21]:
arr1=np.array([[12,13],[32,14]])
arr2=np.array([[15,16],[17,32]])
print(np.concatenate([arr1,arr2],axis=1))#horizontal
print(np.hstack([arr1,arr2]))

[[12 13 15 16]
 [32 14 17 32]]
[[12 13 15 16]
 [32 14 17 32]]


In [22]:
print(np.concatenate([arr1,arr2],axis=0))#verticle
print(np.vstack([arr1,arr2]))

[[12 13]
 [32 14]
 [15 16]
 [17 32]]
[[12 13]
 [32 14]
 [15 16]
 [17 32]]


In [24]:
#splitting
a=np.array([1,2,3,4,5,6])
print(np.array_split(a,3))

[array([1, 2]), array([3, 4]), array([5, 6])]


In [25]:
b=np.array_split(a,3)
print(b[1])#by indexing

[3 4]


In [40]:
#adding and removing elements in arrays
import numpy as np
a=np.array([2,4,6,8])
b=(np.append(a,10))
print(b)
print(np.append(b,[2,3]))
print(np.insert(b,2,3))# array,index,value
print(np.delete(b,2))

[ 2  4  6  8 10]
[ 2  4  6  8 10  2  3]
[ 2  4  3  6  8 10]
[ 2  4  8 10]


In [49]:
#search ,sort,filter
#sort- ascending order
#filter-create new array from an existing array
#search-by indexing

import numpy as np
arr=np.array([3,5,2,6,7,1,9])
print(np.sort(arr1))
s=np.where(arr%2==0)
print(s)

[1 2 3 5 6 7 9]
(array([2, 3], dtype=int64),)


In [46]:
#searching


<function print>

In [57]:
#aggregate funtions in arrays

import numpy as np
s=np.array([2,4,5,6,7,1])
print(np.sum(s))
print(np.min(s))
print(np.max(s))
print(np.size(s))
print(np.mean(s))
print(np.cumsum(s))
print(np.cumprod(s))


25
1
7
6
4.166666666666667
[ 2  6 11 17 24 25]
[   2    8   40  240 1680 1680]


In [70]:
a=[2,3,4,5,6,2,5]
b=[5,6,7,8,9,5,4]
price=np.array(a)
quantity=np.array(b)
print(price,"\n", quantity)
print(np.sum(price))
print(np.cumprod([price,quantity]))

[2 3 4 5 6 2 5] 
 [5 6 7 8 9 5 4]
27
[          2           6          24         120         720        1440
        7200       36000      216000     1512000    12096000   108864000
   544320000 -2117687296]


In [80]:
#statiscal funtion in array
import numpy as np
import statistics as stats
baked_food=[200,300,250,400,500,600,]
a=np.array(baked_food)
print(a)
print(np.mean(a))
print(np.median(a))
print(stats.mode(a))
print(np.std(a))
print(np.var(a))

[200 300 250 400 500 600]
375.0
350.0
200
140.68285846778443
19791.666666666668


In [ ]:
tobaco_cunsumption=[2,3,5,7,8,6,]
